language: node_js
node_js:
  - "8"
before_script:
  - cd ./StormWeb/
  - npm install
  - bower install
  - npm i typescript --save-dev
  - npm run antlr
  - find ./src
  - npm run build

script: npm run test