matrix:
  include:
    - language: node_js
      node_js:
        - 8
      script:
        - cd ./StormWeb/
        - npm install
        - bower install
        - npm i typescript --save-dev
        - npm run antlr
        - find ./src
        - npm run build
        - cd ..
      addons:
        ssh_known_hosts:
          - ssh.cluster026.hosting.ovh.net
      cache:
        directories:
          - StormWeb/node_modules

      before_deploy:
        - openssl aes-256-cbc -K $encrypted_80b985043969_key -iv $encrypted_80b985043969_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa

      deploy:
        provider: script
        skip_cleanup: true
        script: rsync -r --delete-after --quiet -av $TRAVIS_BUILD_DIR/StormWeb/ florentpgd@ssh.cluster026.hosting.ovh.net:~/storm
        on:
          branch: master

    - language: scala
      scala:
        - 2.12.4
      before_script:
        - cd ./engine/
        - sbt "fastOptJS"
        - cd ..
        - cp ./engine/target/scala-2.12/engine-fastopt.js ./StormWeb/js/
      script:
        -
      addons:
        ssh_known_hosts:
          - ssh.cluster026.hosting.ovh.net

      before_deploy:
        - openssl aes-256-cbc -K $encrypted_80b985043969_key -iv $encrypted_80b985043969_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa

      deploy:
        provider: script
        skip_cleanup: true
        script: rsync -r --delete-after --quiet -av $TRAVIS_BUILD_DIR/StormWeb/js/engine-fastopt.js florentpgd@ssh.cluster026.hosting.ovh.net:~/storm/js
        on:
          branch: master
