jobs:
  include:
    - stage: build
      language: node_js
      node_js: 8
      cache:
        directories:
          - ./StormWeb/node_modules
      script:
        - cd StormWeb
        - npm install
        - npm i typescript --save-dev
        - npm run build
    -
      language: scala
      scala:
        - 2.12.4
      cache:
        directories:
          - ~/.sbt
          - ~/.ivy2
      script:
        - cd engine
        - sbt "fastOptJS"
        - cp ./target/scala-2.12/engine-fastopt.js ../StormWeb/js/


    - stage: deploy
      language: bash
      if: branch = master
      addons:
        hosts:
          - ssh.cluster026.hosting.ovh.net
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_80b985043969_key -iv $encrypted_80b985043969_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
      deploy:
        provider: script
        skip_cleanup: true
        script: rsync -r --delete-after --quiet -av $TRAVIS_BUILD_DIR/StormWeb/ florentpgd@ssh.cluster026.hosting.ovh.net:~/storm
    -
      before_deploy:
        - cd StormWeb
        - npm package
        - cd releases
        - zip -r electron.zip storm-linux-x64
      deploy:
        provider: releases
        api_key: "$GITHUB_TOKEN"
        file: ~/Storm/StormWeb/releases/electron.zip
        skip_cleanup: true

notifications:
  email: false

after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL