before_install:
  - openssl aes-256-cbc -K $encrypted_80b985043969_key -iv $encrypted_80b985043969_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

addons:
  ssh_known_hosts:
  - ssh.cluster026.hosting.ovh.net
  sonarcloud:
    organization: "earendil06-github"
    token: $SONAR_TOKEN

jobs:
  include:
  - stage: build
    language: node_js
    node_js: 8
    cache:
      directories:
      - ./StormWeb/node_modules
      - $HOME/.sonar/cache
    script:
    - cd StormWeb
    - npm install
    - npm i typescript --save-dev
    - npm run build
    - chmod u+x ./create-offline.sh && ./create-offline.sh && cp index-offline.html index.html && cp ide-offline.html ide.html
    - sonar-scanner
    - npm run dist
    - npm run test
    deploy:
      provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet -av $TRAVIS_BUILD_DIR/StormWeb/ florentpgd@ssh.cluster026.hosting.ovh.net:~/storm
      on:
        branch: master


  -
    language: scala
    scala:
    - 2.12.4
    cache:
      directories:
      - ~/.sbt
      - ~/.ivy2
    script:
    - cd engine
    - sbt "fastOptJS"
    deploy:
      provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet -av $TRAVIS_BUILD_DIR/engine/target/scala-2.12/engine-fastopt.js florentpgd@ssh.cluster026.hosting.ovh.net:~/cdn/storm/
      on:
        branch: master

notifications:
  email: false

after_success:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh success $WEBHOOK_URL
after_failure:
- wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure $WEBHOOK_URL

