version: 2
jobs:
#  build-test-scala:
#    working_directory: ~/engine
#    docker:
#    - image: openjdk:8
#    environment:
#      SBT_VERSION: 1.2.0
#    steps:
#    - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
#    - run:
#        name: Get sbt binary
#        command: |
#          apt update && apt install -y curl
#          curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
#          dpkg -i sbt-$SBT_VERSION.deb
#          rm sbt-$SBT_VERSION.deb
#          apt-get update
#          apt-get install -y sbt git
#          apt-get clean && apt-get autoclean
#    - checkout
#    - restore_cache:
#        key: sbt-cache
#    - run:
#        name: Compile samplescala dist package
#        command: |
#          sbt clean "fastOptJS"
#    - save_cache:
#        key: sbt-cache
#        paths:
#        - "~/.ivy2/cache"
#        - "~/.sbt"
#        - "~/.m2"

  build-test-ts:
    working_directory: ~/Storm
    docker:
      - image: circleci/node:6.10.3

    steps:
    - checkout
    - run:
        name: update npm
        command: 'sudo npm install -g npm@latest'
    - restore_cache:
        key: dependency-cache-{{ checksum "./StormWeb/package.json" }}
    - run:
        name: install npm dependencies
        command: npm cache clean && chmod +x ./install.sh && ./install.sh

    - run:
        name: build project
        command: chmod +x ./build.sh && ./build.sh

    - save_cache:
        key: dependency-cache-{{ checksum "./StormWeb/package.json" }}
        paths:
        - ~/Storm/StormWeb/node_modules
    - run:
        name: run tests
        command: chmod +x ./test-ts.sh && ./test-ts.sh


workflows:
  version: 2
  build_and_test:
    jobs:
    #- build-test-scala
    - build-test-ts