version: 2
jobs:
  build-test-scala:
    working_directory: ~/Storm
    docker:
    - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.0
    steps:
    - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
    - run:
        name: Get sbt binary
        command: |
          apt update && apt install -y curl
          curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
          dpkg -i sbt-$SBT_VERSION.deb
          rm sbt-$SBT_VERSION.deb
          apt-get update
          apt-get install -y sbt git
          apt-get clean && apt-get autoclean
    - checkout
    - restore_cache:
        key: sbt-cache
    - run:
        name: Compile samplescala dist package
        command: |
          chmod +x ./gen-copy-scala.sh && ./gen-copy-scala.sh
    - save_cache:
        key: sbt-cache
        paths:
        - "~/.ivy2/cache"
        - "~/.sbt"
        - "~/.m2"
    - persist_to_workspace:
        root: engine/target/scala-2.12/
        paths:
        - engine-fastopt.js

  build-test-ts:
    working_directory: ~/Storm
    docker:
    - image: circleci/node:6.10.3

    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "./StormWeb/package.json" }}
    - run:
        name: install npm dependencies
        command: npm --version && npm cache clean && chmod +x ./install.sh && ./install.sh
    - run:
        name: build project
        command: chmod +x ./build.sh && ./build.sh
    - save_cache:
        key: dependency-cache-{{ checksum "./StormWeb/package.json" }}
        paths:
        - ~/Storm/StormWeb/node_modules
    - run:
        name: run tests
        command: chmod +x ./test-ts.sh && ./test-ts.sh

  deploy:
    working_directory: ~/Storm
    steps:
    - attach_workspace:
        at: /tmp/engine/target/scala-2.12/
    - run: cat /tmp/engine/target/scala-2.12/engine-fastopt.js


workflows:
  version: 2
  build_and_test:
    jobs:
    - build-test-scala
    - build-test-ts
    - deploy:
        requires:
        - build-test-scala
        - build-test-ts