# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo/Storm/StormWeb

    steps:
      - checkout
      #- run:
      #    name: list directory
      #    command: ls
      #- run:
      #    name: change directory to storm
      #    command: cd StormWeb
      #- run:
      #     name: list directory
      #     command: ls
      #- run: npm install
      #- run: bower install
      #- run: npm i typescript --save-dev
      #- run: npm run antlr
      #- run: npm run build
      - run:
          name: exec
          command: chmod +x install-all.sh
      - run:
          name: install-all
          command: ./install-all.sh


      # run tests!
      #- run: yarn test

