import {JsonParser} from "../resources/JsonParser";

test('compute modifier', async () => {
    expect(JsonParser.computeModifier(1)).toBe(-5);
    expect(JsonParser.computeModifier(2)).toBe(-4);
    expect(JsonParser.computeModifier(3)).toBe(-4);
    expect(JsonParser.computeModifier(4)).toBe(-3);
    expect(JsonParser.computeModifier(5)).toBe(-3);
    expect(JsonParser.computeModifier(6)).toBe(-2);
    expect(JsonParser.computeModifier(7)).toBe(-2);
    expect(JsonParser.computeModifier(8)).toBe(-1);
    expect(JsonParser.computeModifier(9)).toBe(-1);
    expect(JsonParser.computeModifier(10)).toBe(0);
    expect(JsonParser.computeModifier(11)).toBe(0);
    expect(JsonParser.computeModifier(12)).toBe(1);
    expect(JsonParser.computeModifier(13)).toBe(1);
    expect(JsonParser.computeModifier(14)).toBe(2);
    expect(JsonParser.computeModifier(15)).toBe(2);
    expect(JsonParser.computeModifier(16)).toBe(3);
    expect(JsonParser.computeModifier(17)).toBe(3);
    expect(JsonParser.computeModifier(18)).toBe(4);
    expect(JsonParser.computeModifier(19)).toBe(4);
    expect(JsonParser.computeModifier(20)).toBe(5);
    expect(JsonParser.computeModifier(21)).toBe(5);
    expect(JsonParser.computeModifier(22)).toBe(6);
    expect(JsonParser.computeModifier(23)).toBe(6);
    expect(JsonParser.computeModifier(24)).toBe(7);
    expect(JsonParser.computeModifier(25)).toBe(7);
    expect(JsonParser.computeModifier(26)).toBe(8);
    expect(JsonParser.computeModifier(27)).toBe(8);
    expect(JsonParser.computeModifier(28)).toBe(9);
    expect(JsonParser.computeModifier(29)).toBe(9);
    expect(JsonParser.computeModifier(30)).toBe(10);
});
